
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class Ujikebolehan extends javax.swing.JFrame {
    
    String temp = "";
    Double ti,bt,h1;

    /**
     * Creates new form Ujikebolehan
     */
    public Ujikebolehan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btexit = new javax.swing.JButton();
        bthitung = new javax.swing.JButton();
        btcoba = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        tbideal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tbberat = new javax.swing.JTextField();
        tbnama = new javax.swing.JTextField();
        tbtinggi = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 15, 140, 20);

        jLabel2.setText("Nama ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 50, 60, 14);

        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 80, 50, 14);

        jLabel4.setText("Berat Badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 110, 70, 14);

        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 150, 90, 20);

        jLabel6.setText("Berat Badan Ideal anda adalah ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 230, 240, 14);

        btexit.setText("Keluar");
        btexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexitActionPerformed(evt);
            }
        });
        getContentPane().add(btexit);
        btexit.setBounds(270, 180, 73, 23);

        bthitung.setText("Hitung");
        bthitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthitungActionPerformed(evt);
            }
        });
        getContentPane().add(bthitung);
        bthitung.setBounds(83, 180, 70, 23);

        btcoba.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btcoba.setText("Coba lagi");
        btcoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcobaActionPerformed(evt);
            }
        });
        getContentPane().add(btcoba);
        btcoba.setBounds(170, 180, 80, 23);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(210, 300, 160, 20);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 320, 380, 140);
        getContentPane().add(tbideal);
        tbideal.setBounds(100, 250, 50, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("KG");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 260, 34, 14);
        getContentPane().add(tbberat);
        tbberat.setBounds(140, 110, 60, 30);

        tbnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnamaActionPerformed(evt);
            }
        });
        getContentPane().add(tbnama);
        tbnama.setBounds(140, 50, 220, 30);
        getContentPane().add(tbtinggi);
        tbtinggi.setBounds(140, 80, 60, 30);

        jRadioButton1.setText("Perempuan");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(140, 150, 100, 23);

        jRadioButton2.setText("Laki-laki");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(240, 150, 120, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Cm");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(210, 90, 70, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Kg");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(210, 120, 50, 14);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 480);

        setBounds(0, 0, 416, 511);
    }// </editor-fold>//GEN-END:initComponents

    private void tbnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbnamaActionPerformed

    private void btexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexitActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btexitActionPerformed

    private void bthitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthitungActionPerformed
        if (tbberat.getText().equals("")||tbtinggi.getText().equals("")||tbnama.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Kotak isian elum terisi!");}
        else if(jRadioButton1.isSelected()||jRadioButton2.isSelected())
            try{
                Proses();
                }    
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Inputan ada yang salah");
                }  else {
        JOptionPane.showMessageDialog(null,"Jenis kelamin harus diisi"); 
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_bthitungActionPerformed

    private void btcobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcobaActionPerformed
        tbnama.setText("");
        tbtinggi.setText("");
        tbberat.setText("");
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        tbideal.setText("");
        TA.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btcobaActionPerformed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ujikebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ujikebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ujikebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ujikebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ujikebolehan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TA;
    private javax.swing.JButton btcoba;
    private javax.swing.JButton btexit;
    private javax.swing.JButton bthitung;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tbberat;
    private javax.swing.JTextField tbideal;
    private javax.swing.JTextField tbnama;
    private javax.swing.JTextField tbtinggi;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        ti = Double.valueOf(tbtinggi.getText());
        bt = Double.valueOf(tbberat.getText());
        
        if(jRadioButton1.isSelected()){
            h1 = (ti - 110)*1;
        }
        else if(jRadioButton2.isSelected()){
            h1 = (ti-104)*1;
        }
        temp = Double.toString(h1.intValue());
        
        if (h1<bt){
            tbideal.setText(temp);
            TA.setText("Maaf "+tbnama.getText()+",sepertinya anda Overweight \n\n"
                    + " Banyaklah berolahraga dan hindari makanan berkolesterol");
        }else if(h1 > bt){
            tbideal.setText(temp);
            TA.setText("Maaf "+tbnama.getText()+", sepertinya anda Underweight \n\n"+
                    "Banyaklah mengkonsumsi makanan ynag berkahrohidrat");}
            else{
             tbideal.setText(temp);
             TA.setText("Selamat "+tbnama.getText()+",Berat badan kamu sudah Ideal \n\n"+
                        "Lanjutkan pola hidup sehat yaaaa :)");
                    }
        }
            
        
    }
       
